// Auth
export const SET_IDLE_TIMEOUT = "SET_IDLE_TIMEOUT";

// Users
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_USERS = "LOAD_USERS";

// Errors
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

// System
export const SET_DATA_LOADED_STATUS = "SET_DATA_LOADED_STATUS";
export const RESET_DATA_LOADED_STATUS = "RESET_DATA_LOADED_STATUS";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_MODAL_V2 = "TOGGLE_MODAL_V2";
export const LOAD_TAG_DATA = "LOAD_TAG_DATA";
export const LOAD_PRICING_COLUMN_DATA = "LOAD_PRICING_COLUMN_DATA";
export const LOAD_PRICING_ROW_DATA = "LOAD_PRICING_ROW_DATA";
export const SET_DATA_READY_STATUS = "SET_DATA_READY_STATUS";
export const TRIGGER_ORDER_SAVE = "TRIGGER_ORDER_SAVE";

// Tags

// Clients
export const LOAD_CLIENTS = "LOAD_CLIENTS";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const LOAD_TAG = "LOAD_TAG";
export const REMOVE_TAG = "REMOVE_TAG";

// Companies
export const LOAD_COMPANY_DATA = "LOAD_COMPANY_DATA";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const ADD_COMPANY_CONTACT = "ADD_COMPANY_CONTACT";
export const REMOVE_COMPANY_CONTACT = "REMOVE_COMPANY_CONTACT";

// Orders
export const LOAD_ORDERS = "LOAD_ORDERS";
export const ADD_TO_CLIENT_ORDERS = "ADD_TO_CLIENT_ORDERS";
export const EDIT_ORDER = "EDIT_ORDER";
export const REMOVE_ORDER = "REMOVE_ORDER";

// Order Rows
export const LOAD_ORDER_ROWS = "LOAD_ORDER_ROWS";
export const ADD_NEW_ORDER_ROW = "ADD_NEW_ORDER_ROW";
export const REMOVE_ROW = "REMOVE_ROW";
export const SET_SELECTED_ORDER_ROW = "SET_SELECTED_ORDER_ROW";
export const EDIT_ROW = "EDIT_ROW";

// Payments
export const LOAD_PAYMENTS = "LOAD_PAYMENTS";
export const ADD_NEW_PAYMENT = "ADD_NEW_PAYMENT";
export const EDIT_PAYMENT = "EDIT_PAYMENT";

// Inventory
export const LOAD_INVENTORY = "LOAD_INVENTORY";
export const ADD_TO_INVENTORY = "ADD_TO_INVENTORY";
export const INVENTORY_TEXT_INPUT_CHANGE = "INVENTORY_TEXT_INPUT_CHANGE";
export const EDIT_INVENTORY = "EDIT_INVENTORY";
export const REMOVE_INVENTORY_ITEM = "REMOVE_INVENTORY_ITEM";
